# Generated by Django 6.0 on 2025-12-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
