# Generated by Django 6.0 on 2026-01-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_memories_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('UNLOCK', 'Unlock'), ('INVITE', 'Invite'), ('REMINDER', 'Reminder'), ('INVITE_ACCEPTED', 'Invite_accepted'), ('REACTION', 'Reaction')], max_length=20),
        ),
    ]
