# Generated by Django 5.2.5 on 2026-01-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_recipients_decline_alter_capsule_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memories',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='memories/'),
        ),
    ]
